### ISSUE TITLE
[feature] support google actions v2 API

### ISSUE THREAD

**Issue by nealrs** [bespoken/virtual-google-assistant#18]
I know this library current supports v1 and that many (if not most) actions are built on it, but you can no longer build v1 actions, and the new media response object (long form audio player) is only available with v2.

**Comment by westlakem** [comment]
Any updates on this?

**Comment by jkelvie** [comment]
Hi @westlakem - we do not have this scheduled yet. We will let you know as soon as we know when it will be available.

**Comment by ecruzado** [comment]
Update request to support DialogFlow v2. Follow V1 to V2 mapping https://dialogflow.com/docs/reference/v1-v2-mapping. To use v1 or v2 response validate onePlatformApiVersion key on agent.json

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-google-assistant/pull/19 this PR is to support the new fulfillment format on DialogFlow v2
