### ISSUE TITLE
Will the library support conversational test cases

### ISSUE THREAD

**Issue by AngavaiS** [bespoken/virtual-google-assistant#37]
Hi Juan,

Thanks for all your help. I do have one more question.
Since I am learning and I am a tester.
I am learning Unit testing now.
So the questions may sound silly.

Do the library support conversational testing ?
If the conversation does not contain the intents.

describe(‘Location Details and change location,  function () {

    it('it should return welcome intent', function () {
     	res2 = await ga.utter(‘open Starbucks’);
         });

    it('it should return location intent', function () {
		res2 = await ga.utter(‘get me nearest store’);
          });

    // The below two are not intents.
    it('it should return different location question', function () {
       res2 = await ga.utter(‘different Location’);
    });

    it('it should return different location details’, function () {
       res2 = await ga.utter(‘Walnut Creek CA’);
    });
}); 

Thanks,
Angavai S.

**Comment by AngavaiS** [comment]
Juan and team is so awesome in supporting people @jperata Thanks for all your help in solving my issue. @jperata , you are awesome and so helpful :)

**Comment by jperata** [comment]
Thank you for using our tools!
