### ISSUE TITLE
Context maintained in Dialog flow is not getting picked up

### ISSUE THREAD

**Issue by AngavaiS** [bespoken/virtual-google-assistant#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Recently I understood that the context that has been maintained in Dialog Flow is not getting picked up. After I tried saving the context in the code, I am getting response. Is that feature available or am I missing something ?

**Comment by jperata** [comment]
Solved in #22
