### ISSUE TITLE
Fix support for Google Cloud functions as well as lamdas

### ISSUE THREAD

**Issue by dmarvp** [bespoken/virtual-google-assistant#61]
### Description:
Support for Google Cloud functions broke with #60  

### Expected behavior
Google virtual assistant should support lambdas as well as google cloud functions.

### Actual behavior
#60 added support for lambdas but broke support for Google cloud functions.

### Additional context
As per John's comment:
https://github.com/bespoken/virtual-google-assistant/pull/60#issuecomment-674122199
We should be able to support both.

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-google-assistant/pull/62

**Comment by dmarvp** [comment]
Closing as fixed. Will reopen if we get further feedback.
